name: CI
on:
  push:
    branches:
      - main
jobs:
  receive_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2
        
      - name: Configuração do FTP
        uses: wuakitv/ftp-upload-action@v2.1
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./path/to/markdown/files
          remote-dir: /path/on/ftp/server
# vamos oooooo